### ISSUE TITLE
Add ners570f24 Students to Repo

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f24-SpMV#22]
The purpose of this issue is to add all the students in ners570f24 to this repo for collaboration on upcoming activities.

To complete this issues the following students should be added
- [x] aalmohri
- [x] athenafh
- [x] bkhardy
- [x] bkierulf
- [X] bkochuna
- [x] brickd
- [x] davidgw
- [x] dbloc
- [x] emahler
- [x] ffarha
- [x] jsayut
- [X] kcvaughn
- [x] looyujun
- [x] magranad
- [x] moonbh
- [x] namano
- [x] nazemi
- [x] niloy
- [x] panteran
- [x] rsshast
- [x] rswame
- [x] ryakkund
- [x] sadid
- [x] skenma
- [x] vshreyas
- [x] wmaxon
- [x] xianyu
- [x] yulupeng

**Comment by bkochuna** [comment]
This is blocked by #1

**Comment by bkochuna** [comment]
@KyleVaughn does not have admin access to the repo, so @bkochuna has to add teh students.

**Comment by bkochuna** [comment]
Passing to @KyleVaughn to review and close

**Comment by KyleVaughn** [comment]
Looks right to me!
