### ISSUE TITLE
Add ners570f24 Students to Kanban Project

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f24-SpMV#23]
The purpose of this issue is to add all the students in ners570f24 to the associated kanban project for collaboration on upcoming activities.

To complete this issues the following students should be added
- [x] aalmohri
- [x] athenafh
- [x] bkhardy
- [x] bkierulf
- [X] bkochuna
- [x] brickd
- [x] davidgw
- [x] dbloc
- [x] emahler
- [x] ffarha
- [x] jsayut
- [X] kcvaughn
- [x] looyujun
- [x] magranad
- [x] moonbh
- [x] namano
- [x] nazemi
- [x] niloy
- [x] panteran
- [x] rsshast
- [x] rswame
- [x] ryakkund
- [x] sadid
- [x] skenma
- [x] vshreyas
- [x] wmaxon
- [x] xianyu
- [x] yulupeng

**Comment by bkochuna** [comment]
This is blocked by #1

**Comment by KyleVaughn** [comment]
Added everyone. Closing.
