### ISSUE TITLE
Develop a High Level Design in Groups

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f24-SpMV#55]
## Background
In software design and engineering, it is important to think about the OO software design, before coding. In this issue we want to meet our learning objective of demonstrating the skill to create a UML class diagram.

## Tasks
- [x] Each group should work on activity 1 and comment in the issue to provide a sketch of their classes with attributes.
- [x] Each group should work on activity 2 and comment in the issue to provide a sketch illustrating the relationships between classes.

## Definition of Done
There are two comments from each of the groups. Each comment should include the image(s) of their Class Diagrams for each activity.

**Comment by bkochuna** [comment]
@KyleVaughn can you review this issue to see if it is complete and coherent. It has a clear definition of done, and a clear set of tasks. It should also be assigned to a milestone and have a project status. If you agree its a valid issue, move to selected.

**Comment by KyleVaughn** [comment]
Looks good. Moved to selected

**Comment by AndrewPanter** [comment]
![IMG_0204](https://github.com/user-attachments/assets/da7d7a3c-b525-4412-9ae1-ac3c98d10db9)
![IMG_0205](https://github.com/user-attachments/assets/7565cea1-c1eb-4308-833b-c8241fb9fecd)
Class Diagrams for group 1

**Comment by davidgw-umich** [comment]
![spmv](https://github.com/user-attachments/assets/366f8d3a-261f-49a1-9dbc-4031d13eeff4)

**Comment by bjorngkierulf** [comment]
![IMG_0019](https://github.com/user-attachments/assets/1e7920b1-d12f-4bff-9f10-42d3e1ad695f)

**Comment by wcurtmaxon** [comment]
![IMG_3404](https://github.com/user-attachments/assets/424f3c0a-a8b9-479b-b312-f8656c256f6a)

**Comment by bkochuna** [comment]
Realized that the second activity should fall under this issue. Updating issue, to include new task and revised definition of done for second lab activity.

**Comment by davidgw-umich** [comment]
group memebers: swawe, nick amano, athena, kennegh
![class tree](https://github.com/user-attachments/assets/9a928660-c677-4961-af7f-205eb6ff6a47)

**Comment by wcurtmaxon** [comment]
![IMG_3405](https://github.com/user-attachments/assets/8f6a734f-b6fb-4cb4-9f93-ff0e4dcaceb7)
 Loc Duong 
Niloy Gupta 
Evan Mahler
Curtis Maxon

**Comment by MattGranados** [comment]
![Note Oct 4, 2024](https://github.com/user-attachments/assets/9621b7b1-dc18-4141-a460-4bc79fefbd8c)
2nd Class Diagram for Matthew Granados, Declan Brick, Yulu Peng, Xianyu Liu

**Comment by AndrewPanter** [comment]
![unnamed](https://github.com/user-attachments/assets/548d46be-9101-412f-986f-76401f06ca10)
Hierarchy Diagram for group 1 - Andrew Panter, Ravi Shastri, Farha Farhana, and Moon Hazarika

**Comment by jsayut1** [comment]
![image](https://github.com/user-attachments/assets/4f56b78e-ceec-4859-808e-4196bbdde240)

**Comment by shreyasv11** [comment]
![1](https://github.com/user-attachments/assets/f116d922-6691-4975-bc88-ccb7635f128b)
Class Attribute diagram for Shreyas Vajjhala (uniqname- vshreyas)

**Comment by shreyasv11** [comment]
![2](https://github.com/user-attachments/assets/6c1c2cec-d807-4977-b01e-efe09ff47d4d)
Hierarchical diagram for Shreyas Vajjhala (vshreyas)

**Comment by looyujun** [comment]
[2024-10-05-JunLoo- - NERS570Lab06.pdf](https://github.com/user-attachments/files/17267235/2024-10-05-JunLoo-.-.NERS570Lab06.pdf)

Class and Hierarchal Diagram for Yu Jun Loo (looyujun)

**Comment by srsadid** [comment]
![img1](https://github.com/user-attachments/assets/5857adc6-655b-4ed2-b73d-886c0547975c)
![image](https://github.com/user-attachments/assets/0b993797-6a6e-4a56-85d0-35f29da05814)
