### ISSUE TITLE
Assign Issues to Students for HW3

### ISSUE THREAD

**Issue by bkochuna** [bkochuna/ners570f24-SpMV#56]
## Background
This task is about making sure we have all issues assigned to each student.

The students are:
| Student | user                   | Feature    | Test | Review 1 | Review 2 |
| -------- | --------------- | --------- | ---- | --------- | ---------- |
| aalmohri | @S-A-Almohri | #6 |  #43 | #35 | #52 |
| athenafh | @athenafhl |  #28  |  #51 | #12 | #8 |
| bkierulf | @bjorngkierulf | #26 | #8  | #6 | #42 |
| brickd | @DecBrick | #15 | #30 | #47 | #44 |
| davidgw | @davidgw-umich | #16 | #20 | #28 | #40 |
| dbloc | @dbloc-umich | #12 | #19 | #15 | #20 |
| emahler | @eemahler | #46 | #34 | #38 | #9 |
| ffarha | @ffarha | #25 | #44 | #2 | #18 |
| jsayut | @jsayut1 | #14 | #52 | #36 | #11 |
| looyujun | @looyujun | #13 | #50 | #39 | #41 |
| magranad | @MattGranados | #27 | #33 | #49 | #17 |
| moonbh | @MoonBH-UoM | #29 | #53 | #45 | #50 |
| namano | @nickamano | #36 | #40 | #5 | #32 |
| nazemi | @amirnzm | #38 | #11 | #3 | #19 |
| niloy | @NiloyGupta-UM | #49 | #42 | #4 | #43 |
| panteran | @AndrewPanter | #2 | #32 | #25 | #54 |
| rsshast | @rsshast | #37 | #54 | #14 | #34 |
| rswame | @swame2000 | #39 | #10 | #48 | #53 |
| ryakkund | @ryakkund | #48 | #17 | #13 | #10 |
| sadid | @srsadid | #47 | #18 | #29 | #21 |
| skenma | @kaleisss | #35 | #31 | #27 | #7  |
| vshreyas | @shreyasv11 | #4 | #7 | #16 | #31 |
| wmaxon | @wcurtmaxon | #45 | #41 | #26 | #30 |
| xianyu | @xianyu2023umich | #5 | #21 | #37 | #51 |
| yulupeng | @PengYululu | #3 | #9 | #46  | #33 |

The issues are:
- [x] #2 
- [x] #3
- [x] #4 
- [x] #5 
- [x] #6 
- [x] #7 
- [x] #8 
- [x] #9 
- [x] #10 
- [x] #11 
- [x] #12 
- [x] #13 
- [x] #14 
- [x] #15 
- [x] #16 
- [x] #17 
- [x] #18 
- [x] #19 
- [x] #20 
- [x] #21 
- [x] #25 
- [x] #26 
- [x] #27 
- [x] #28 
- [x] #29 
- [x] #30 
- [x] #31 
- [x] #32 
- [x] #33 
- [x] #34 
- [x] #35 
- [x] #36 
- [x] #37 
- [x] #38 
- [x] #39 
- [x] #40 
- [x] #41
- [x] #42 
- [x] #43 
- [x] #44 
- [x] #45 
- [x] #46 
- [x] #47 
- [x] #48 
- [x] #49 
- [x] #50
- [x] #51 
- [x] #52 
- [x] #53 
- [x] #54 

## Tasks
The tasks in this issue is to make sure each student is assigned 4 issues.

## Definition of Done
The description is updated so that each student has 4 issues listed next to their name and the box is checked.
The description is also updated so that each issue in that list is checked to mark it has been assigned.

**Comment by KyleVaughn** [comment]
Looks good! Closing.
